module.exports = {
  purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        text01: 'var(--color-text-01)',
        text02: 'var(--color-text-02)',
        text03: 'var(--color-text-03)',
        link01: 'var(--color-link-01)',
        link01Hover: 'var(--color-link-01-hover)',
        link01Active: 'var(--color-link-01-active)',
        link01Disabled: 'var(--color-link-01-disabled)',
        bg01: 'var(--color-bg-01)',
        bg02: 'var(--color-bg-02)',
        bg03: 'var(--color-bg-03)',
        bg04: 'var(--color-bg-04)',
        pageBg01: 'var(--color-page-bg-01)',
        pageBg02: 'var(--color-page-bg-02)',
        pageBg03: 'var(--color-page-bg-03)',
        btnBg01: 'var(--color-btn-bg-01)',
        btnBg02: 'var(--color-btn-bg-02)',
        btnBg03: 'var(--color-btn-bg-03)',
        btnBg04: 'var(--color-btn-bg-04)',
        btnGradientBg01: 'var(--color-btn-gradient-bg-01)',
        btnGradientBg02: 'var(--color-btn-gradient-bg-02)',
        btnShadow01: 'var(--color-btn-shadow-01)',
        shadow01: 'var(--color-shadow-01)',
        shadow02: 'var(--color-shadow-02)',
        border01: 'var(--color-border-01)',
        border02: 'var(--color-border-02)',
        textGray: 'var(--color-1inch-gray)',
        blueAccent: 'var(--color-blue-accent)',
        linkBlue: 'var(--color-link-blue)',
        commonText01: '#fff',
        commonText02: '#6c86ad',
        textGreen: '#23c68b',
        borderLightGrey: 'var(--color-border-lightGrey)',
        darkMainBlue: 'var(--color-darkMainBlue)',
        iconButtonActive: 'var(--color-iconButtonActive)',
        bgIconButton: 'var(--color-bgIconButton)',
        iconButton: 'var(--color-iconButton)',
        bgBlackInput: 'var(--color-bgBlackInput)',
        blackInput: 'var(--color-blackInput)',
        textDropdown: 'var(--color-textDropdown)',
        textBlue: '#59f',
        subCard: 'var(--color-subCard)',
        warningText03: 'var(--color-warningText03)',
        bg05: 'var(--color-bg-05)',
        routingBox: 'var(--color-routing-box)',
      },
      width: {
        inherit: 'inherit',
      },
      minWidth: {
        '16px': '16px',
        '60px': '60px',
        '64px': '64px',
        172: '172px',
        350: '350px',
      },
      maxWidth: {
        420: '420px',
        430: '430px',
        480: '480px',
        1400: '1400px',
      },
      minHeight: {
        '40px': '40px',
        540: '540px',
      },
      backgroundImage: {
        '1inch-page-bg-01': 'var(--color-page-bg-01)',
        '1inch-btn-gradient-bg-01': 'var(--color-btn-gradient-bg-01)',
        '1inch-btn-gradient-bg-02': 'var(--color-btn-gradient-bg-02)',
      },
      screens: {
        '1inchSm': '520px',
        '1inchMd': '720px',
        '1inch940': '940px',
        '1inchLg': '1024px',
        '1inchXl': '1400px',
        // 'maxLogo1200': { 'max': '1200px' },
        // 'maxLg': { 'max': '1024px' },
        // 'maxLogo800': { 'max': '800px' },
        // 'maxMd': { 'max': '720px' },
        // 'maxSm': { 'max': '520px' },
        // '1inchlg': '1025px',
        // logo1200: '1200px',
      },
      fontFamily: {
        roboto: "'Roboto', 'serif'",
      },
      order: {
        reverse: '-1',
      },
      spacing: {
        '22px': '22px',
        '27px': '27px',
        '34px': '34px',
        '46px': '46px',
        '82px': '82px',
        '420px': '420px',
      },
      boxShadow: {
        '1inchShadow01': 'var(--color-shadow-01)',
      },
      borderRadius: {
        '14px': '14px',
        '20px': '20px',
      },
      gridTemplateColumns: {
        content: '1fr 480px',
        referralCard: '60px 1fr',
        cellHeader: '24px 1fr',
      },
      transitionProperty: {
        height: 'height',
      },
      fontSize: {
        '13px': '13px',
        '32px': '32px',
      },
      lineHeight: {
        '26px': '26px',
        '46px': '46px',
      },
    },
    screens: {
      logo1200: { max: '1200px' },
      lg: { max: '1024px' },
      logo800: { max: '800px' },
      md: { max: '720px' },
      sm: { max: '520px' },
    },
  },
  variants: {
    transitionProperty: ['responsive', 'motion-safe', 'motion-reduce'],
    extend: {},
  },
  plugins: [],
};
